- name: "Remove Swap From fstab"
  mount:
          path: "swap"
          fstype: "swap"
          state: absent
  register: swap_status

- name: "SwapOff"
  command: "swapoff -a"
  when: swap_status.changed == True

- name: "Create Repository For Kubernetes Packages"
  yum_repository:
          name: "kubernetes"
          description: "Kubernetes"
          baseurl: 'https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch'
          enabled: 1
          gpgcheck: 1
          repo_gpgcheck: 1
          gpgkey: 'https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg'

- name: "Install 'kubeadm' , 'kubelet' , 'kubectl' and 'iproute-tc' packages"
  package:
          name:
                  - "kubeadm"
                  - "iproute-tc"
          state: present

- name: "Start And Enable 'kubelet'"
  service:
          name: "kubelet"
          state: started
          enabled: True

- name: "Configure Master"
  include: "master.yml"
  when: ansible_facts.default_ipv4.address in groups.private_kubernetes_master

- debug:
        var: token_status

- name: "Slave Configuration Tasks"
  include: "slave_config.yml"
  when: ansible_facts.default_ipv4.address in groups.private_kubernetes_slave

- name: "Destroy Token On Master"
  kubeadm_token:
          token: "{{ token_status.token_info.token }}"
          action: delete
  when: ansible_facts.default_ipv4.address in groups.private_kubernetes_master
